apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: inst-a
  namespace: argocd
spec:
  project: default
  source:
    repoURL: bvtacr.azurecr.io/helm/simple-chart
    chart: simple-chart
    targetRevision: 0.4.0
    helm:
      releaseName: afa6493ed2321eabf340f65eeec2bb95764d4dcc
      values: |
          StringVal: git35a1ae0cf874
  destination:
    server: https://kubernetes.default.svc
    namespace: test
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
