apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: soap-quantity
  namespace: argocd
spec:
  project: default
  source:
    repoURL: wodemo.azurecr.io/helm/soap-quantity
    chart: soap-quantity
    targetRevision: 1.0.0
    helm:
      releaseName: 72f7bd5d3566300d3de2a7c2df79b8799dc77882
      values: |
          Quantity: 500
          Unit: ml
  destination:
    server: https://kubernetes.default.svc
    namespace: monday-line-1
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
