apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: inst-b
  namespace: argocd
spec:
  project: default
  source:
    repoURL: bvtacr.azurecr.io/helm/simple-chart
    chart: simple-chart
    targetRevision: 0.4.0
    helm:
      releaseName: 52398ba5f3c75e1d7f0041701f3a592a9679d5e2
      values: |
          StringVal: git106885eb58f0
  destination:
    server: https://kubernetes.default.svc
    namespace: test
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
