apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: st35a1ae0cf868
  namespace: argocd
spec:
  project: default
  source:
    repoURL: bvtacr.azurecr.io/helm/simple-chart
    chart: simple-chart
    targetRevision: 0.4.0
    helm:
      releaseName: 51c7cfd432cd2a1da373d833bf6ff8dc47b17cf1
      values: |
          StringVal: git35a1ae0cf867
  destination:
    server: https://kubernetes.default.svc
    namespace: test
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
