apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stb44dc9770179
  namespace: argocd
spec:
  project: default
  source:
    repoURL: bvtacr.azurecr.io/helm/simple-chart
    chart: simple-chart
    targetRevision: 0.4.0
    helm:
      releaseName: c83ea67f1783e68da6171c11e4b556cbf739d998
      values: |
          StringVal: gitb44dc9770178
  destination:
    server: https://kubernetes.default.svc
    namespace: test
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
