apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stef6956687eca
  namespace: argocd
spec:
  project: default
  source:
    repoURL: bvtacr.azurecr.io/helm/simple-chart
    chart: simple-chart
    targetRevision: 0.4.0
    helm:
      releaseName: 51418bd88f1139c420629fa9c138e9191ead9479
      values: |
          StringVal: gitef6956687ec9
  destination:
    server: https://kubernetes.default.svc
    namespace: test
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
