apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: st106885eb58df
  namespace: argocd
spec:
  project: default
  source:
    repoURL: bvtacr.azurecr.io/helm/simple-chart
    chart: simple-chart
    targetRevision: 0.4.0
    helm:
      releaseName: 9ac065ef33ee37a594b6fb5975ed7b3ae60d27dd
      values: |
          StringVal: git106885eb58de
  destination:
    server: https://kubernetes.default.svc
    namespace: test
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
