apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: inst-a
  namespace: argocd
spec:
  project: default
  source:
    repoURL: bvtacr.azurecr.io/helm/simple-chart
    chart: simple-chart
    targetRevision: 0.4.0
    helm:
      releaseName: 680aa1185db1d111f6484b8da119f40e0b2dadbb
      values: |
          StringVal: git106885eb58f0
  destination:
    server: https://kubernetes.default.svc
    namespace: test
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
