apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: soap-line-1
  namespace: argocd
spec:
  project: default
  source:
    repoURL: wodemo.azurecr.io/helm/soap-quantity
    chart: soap-quantity
    targetRevision: 1.0.0
    helm:
      releaseName: bd9d46a2e19ef1da643688c5e61024f66f33c153
      values: |
          Quantity: 1
          Unit: batch
          Line: line-1
          Flavor: lavender
  destination:
    server: https://kubernetes.default.svc
    namespace: line-1-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
